### ISSUE TITLE
Shoud callbacks be applied?

### ISSUE THREAD

**Issue by IvoPereira** [eddyystop/feathers-service-verify-reset#1]
Hello,

I am not totally sure on how to implement the e-mail sending.

I was able to implement every hook and services, however, after seeing this function (copied from your example) I was not totally sure if I needed to implement to e-mail sending based on each parameters:

```
function emailer(action, user1, params, cb) {
    console.log(`-- Sending email for ${action}`);
    const provider = params.provider;
    const route = provider === 'rest' ? 'rest' : 'socket';

    switch (action) {
        case 'resend': // send another email with link for verifying user's email addr
            console.log(`Dear ${user1.username}, please click this link to verify your email addr.`);
            console.log(`  http://localhost:3030/${route}/verify/${user1.verifyToken}`);
            break;
        case 'verify': // inform that user's email is now confirmed
            break;
        case 'forgot': // send email with link for resetting forgotten password
            console.log(`Dear ${user1.username}, please click this link to reset your password.`);
            console.log(`  http://localhost:3030/${route}/reset/${user1.resetToken}`);
            break;
        case 'reset': // inform that forgotten password has now been reset
            break;
        default:
            break;
    }

    cb(null);
}
```

Am I missing something?

Thanks

**Comment by eddyystop** [comment]
The function will be called whenever one of the `action` occur. You can no-op any for which you don't want to send an email, though `verify` and `forgot` would usually be needed.

Your subject mentions callbacks. Sending an actual email would be async async. You would want to use the `emailer` callback to pass back any error condition, and that would be passed to the `verifyReset.create` callback.

The example should be clearer`. I'll add that in the next few days.

**Comment by IvoPereira** [comment]
Sorry, I've been on vacations.

So every action that needs an e-mail to be sent, I should use an e-mail sending library to send e-mails for it, right?

I've understood that I should use only the actions I would be using, however the e-mail send itself should be made by me using another library, exactly?

Thanks

**Comment by eddyystop** [comment]
Yes, use some other package/library/service to send the emails. You can send emails only for those actions you feel emails are needed for.

**Comment by IvoPereira** [comment]
Thanks! Solved! 👍
