### ISSUE TITLE
simplify verifyToken to support SMS verification

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#10]
sometimes we prefer SMS or other mobile ways to send verify and reset tokens instead of email, and then let the user input the recieved token in the app. Here the token cannot be too long or too complicated, or it is difficult to input. Typicllay it would be 4 or 6 digital numbers.

so i suggest providing an option to generate simple 6-digit token instead of tje long hashed one.

**Comment by eddyystop** [comment]
I assume the server will sometimes want the 30-char slug and other times a 6-digit one.

The dev controls when and how `verifyHooks.addVerification()` is called. So a param can be introduced describing the type of slug. Basically the problem is being passed over to the dev.

`verifyReset.sendResetPassword(...)` is issued by the client either via web sockets or REST. I don't think its appropriate for the client to state the type of token as a hacker could force a 6-digit slug and have a weaker target to attack. But I could be wrong.

The easiest approach for the dev that I can think of, that is also secure, is to have a separate route for the 6-digit slug. There would have to be some permission control on the route. It could be a callback for the dev to handle, but I'm not sure how the dev would decide on the permission.

What are your thoughts?

**Comment by beeplin** [comment]
Some thoughts: 

The workflow for the 6-digit slug is quite different from that of the 30-char one. The 30-char one is for email: you sent an email with a link containing the slug, and then use a (server-side or client-side) router to handle the URL. The URL is clicked from an email so we don't know which newly signed-up user does the click, and we have to search for the users collection in the database to match the correct user and make it verified.

But the 6-digit slug is for SMS: you send a text message to the new user's cellphone, and then he/she inputs the digits into your app -- **here he/she is still in our app and we know who is initiating the verification, and we can make him/her only have one chance to try**. If failed once, the slug is expired, and he/she has to re-verify with a new 6-digit slug. 

So technically I guess this 6-digit SMS way is actually more secure -- people cannot try again and again for different slugs. Only on chance. And we verify with not only a slug, but a combination of the slug and the current user. 

Therefore, I don't think safety is a big issue, and here is my suggestion:

 Add a `cellphone` field and a `verifyMethod` (err, cannot think of a better name...) field to the `users` service, and when signing up from the client side, the users can choose if they want email or cellphone verification:

``` js
feathers.service('users').create({
  username: xxx, 
  email: xxx, 
  cellphone: xxx, 
  password: xxx,
  verifyMethod: 'email' // or 'cellphone'
})
```

Then on the server side, we generate a 6-digit or a 30-char slug based on the `verifyMethod`, and then we could send it via email or SMS. And when user chooses the 6-digit way, on the client side we provide an input field for the slug (much simpler than handling the URL routes for the 30-char way.)

Just a rough thought. Maybe have big holes in it...

**Comment by eddyystop** [comment]
First, what do you think of voiding the email reset password token in the user record if an invalid token is attempted? I have experienced a few long delays before getting a reset email.  Long enough that I asked again for a reset email. Voiding the token could result in a user trying the link on the first email and failing; then the link on the second email would also fail. So maybe this wouldn't be a good idea.

So the idea is to have a new path to issue an SMS token, and another new path to reset the password given the SMS token and the new password. The SMS token is voided if the given token is invalid.

The present emailer could check to see if the SMS or email token are set and take the appropriate action. However both may be set, so it may be better to pass an SMS handler callback whose sole responsibility is to send an SMS token for password reset.

I'm assuming in all this that the SMS token is only needed for password reset,.

**Comment by beeplin** [comment]
Sorry I only thought of `signup` and forgot whole other things.

I agree that the logic to handle SMS password reset should also be different from that of email. We could keep all the logic for email untouched, and design a new logic for SMS. Say, for email, an invalid verify/reset doesn't void the slug, but for SMS it does. 

So the only problem left might be how to design a new API to handle both email verify/reset and SMS verify/reset. Current API is designed solely for email. I suggest changing the client API to this (just for example):

``` js
verifyReset.unique({ 
  username: xxx, 
  email: xxx, 
  cellphone:xxx 
}, null, false, (err) => { // in the option params user can provide email or cellphone or both

users.create({ 
  username: xxx, 
  email: xxx, 
  cellphone:xxx, 
  password: xxx,
  ..
}, (err, user) => { ... }); // same, use can provide email or cellphone or both in the opitions. (If both, maybe we should verify both email and SMS? Seems a little bit awkward.... Maybe we chould make cellphone and email exclusive, and the user can only choose one? ) 

verifyReset.resendVerify({
  email:xxx,
  cellphone: xxx,
}, (err, user) => { ... }) // user can choose either way, and on the server side we use different logic to handle each way.

verifyReset.verifySignUp({
  slug :xxxx,
  type: 'email' // or 'cellphone'
}, (err, user) => { ... }); // verify based on type. If 'email' then server doesn't expire the slug when failed; if 'cellphone' then expire it.

verifyReset.authenticate({
  email, 
  cellphone,
  password
}, (err, user) => { ... }); // user can choose which way to log in.

verifyReset.sendResetPassword({
  email, 
  cellphone
}, (err, user) => { ... }); // user can choose which way to reset, so different logic can be handled on the server side.

verifyReset.saveResetPassword({
  slug,
  password, 
  type, // 'email' or 'cellphone'
}, (err, user) => { ... }); // handle reset either from email or from cellphone

verifyReset.changePassword({
  oldPassword, 
  newPassword, 
  currentUser, 
  notification: 'email' // or 'cellphone'
}, (err, user) => { ... });  // can choose to send the notification via email or via cellphone.

verifyReset.changeEmail({
  password, 
  newEmail, 
  currentUser, 
  notification: 'email' // or 'cellphone'
}, (err, user) => { ... }); // can choose to notify via either way.

verifyReset.changeCellphone({
  password, 
  newCellphone, 
  currentUser, 
  notification: 'email' // or 'cellphone'
}, (err, user) => { ... }); // can choose to notify via either way.
```

The basic idea is to treat email and cellphone equally as a possible way to do verify/reset (of coz in future it may have more other ways). On the server-side, different handling logic could be done according to the params options passed from the client. If `email` related options are present, then use the email handling logic; if `cellphone`, use a different logic.

**Comment by beeplin** [comment]
Or we could abstract the concepts a little more: it's not about email or SMS or other verify/reset channels. It's just two fundamental ways for the user to send the slug back to our app: 
1. provide the user a URL containing the slug (either via email or via SMS, it's the same -- yes SMS could also include a URL and people can tap it on a smartphone and get redirected to our webpage), and when the user clicks it, the slug is sent back via routing. This way the user don't have to manually type the slug in, (just click), so the slug could be long and complex.
2. provide the user a short simple slug (either via email or via SMS... the same too), and let user manually input the slug in our app. Here no need to do the routing thing, but the slug cannot be too long since the user has to type it in.

So it's not about email or SMS or something else, but about to types of slugs:  **long slug for URL** and **short slug for TYPING IN**.  Short slug is typed into our app, and therefore comes together with the current user info, and can be invalided after one wrong try; long slug is send from outside of our app, and therefore has no user info coming together, and only expires after the given time.

So the `type = 'email'` or `type = 'cellphone'` above could be changed to `type = 'long'` and `type = 'short``. Or just make two different slug options, say: 

``` js
verifyReset.saveResetPassword({
  longSlug,
  shortSlug,
  password, 
}, (err, user) => { ... }); 
```

Hence in some situations we could also send long slug to SMS, or short slug to email, and it's open to any other possible communication channels like whatsapp, facebook, etc. This way we make this package not only for email verify/reset, but a universal verify/reset interface.

**Comment by beeplin** [comment]
I think this is no longer just about SMS support but about some more universal concerns. Will close this one and open another issue for it.
