### ISSUE TITLE
`changeEmail` also has the previous issue of hashing password twice

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#11]
patch should be used rather than update in changeEmail, too.

**Comment by beeplin** [comment]
same for `changePassword`.

**Comment by beeplin** [comment]
did more tests, finding `resendVerifySignUp` also having this problem.

**Comment by eddyystop** [comment]
Remaining `users.update` changed to `users.patch` in npm 0.6.1.

**Comment by eddyystop** [comment]
I'll work on your issues this weekend. Thanks for the info.

**Comment by beeplin** [comment]
I did some tests with my hooks, and everything now runs OK. Seems solved. Good job!
