### ISSUE TITLE
emailer function now has wrong user param

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#14]
``` js
  app.configure(verifyReset({
    emailer: emailer
  }));
...
const emailer = function (action, user, params, cb) {
// user should be user._doc here
}
```

**Comment by eddyystop** [comment]
I left a question for the core team and am awaiting a reply.

**Comment by eddyystop** [comment]
I'm seeing the emailer get the newly patched user item on emailer action `resend`. Please expand on the issue.

**Comment by beeplin** [comment]
It is OK now after updating my packages. never mind.
