### ISSUE TITLE
support "verification code" mode

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#15]
Sending a **verification url** to user's email is the old and traditional way to do verify/reset. But nowadays people use mobile phones or social network systems much more frequently than emails. Some young people even don't have their own email address  -- you have to contact them via facebook, twitter, line, or wechat/qq in China. 

Therefore today we get a different way to do verify/reset: not sending a **url** to people's email and wait for them clicking it, but just sent a **verification code** (long or short, it depends) to any type of address the user is trying to verify, no matter it is an email, or a cellphone number SMS, or a facebook message, or a line message, etc.

After the user received this code, they have to manually input into our app **both the account name they are trying to verify/reset, and the code they received**. Both the two info must be correct, or the verify/reset is invalidated and the code is expired. The use has to ask for another code again.

This way, when verifying/resetting, we can match not only the code, but also the user account name, and the user has only one chance to try. This helps avoiding hacking, and therefore the code doesn't have to be very long. [0-9a-zA-Z]{6} is always enough, and it is easy to input on a cellphone.

I think this new **verification code** way is used more and more widely compared with the old **verification url** way, and hence suggest that this package should also support this code mode. 

We don't need to break the current API to support this code mode. Just an expansion of API should be enough, say, like this:

When the user is signing up in our app: 

``` js
app.service('users').create({
  email: 'a@b.com',
  username: 'beeplin',
  cellphone: '5101112222',
  password: 'xxxxxx',
  primaryContactMethod: 'cellphone', // 'email' by default, the target to send to url/code to. any better name?
  verificationType: 'code' // 'url' by default. generates long slug for url, and short slug for code. any better name?
})
```

Then the verification URL/code is sent via email or SMS. If the mode is URL, after the user clicks the link and is routed to our page, `verifySignUp` is called with the slug embedded in the URL. If the mode is code, our app directs the user to a new page and let him/her input the code he/she received, together with his/her email or cellphone (depends on the `primaryContactMethod` he/she chose just before. Then the `verifySignUp` is called with the two info:

``` js
verifyReset.verifySignUp = function (slugOrOptions, callback) { ... }
```

when `slugOrOptions` is a string, it is the slug, and this means the traditional verification URL mode. Do the verify as we did before, nothing new;

when `slugOrOptions` is an object, it is a map for options, and this means the new verification code mode. The option could be like:

``` js
{
  email: 'a@b.com',
  slug: 'xxxxxx'
}
```

This means the user is trying to verify the email `a@b.com` with a received code `xxxxxx`. Do the verification and return the result/error to the user.

The key point here is that, instead of passing a slug string in, we could also pass an option object in, having a finer control of the user's verify/reset behavior, without breaking the existing API syntax.

The `sendResetPassword`, `saveResetPassword` can also be extended in this way.

I'd like to know how you think about this?

**Comment by eddyystop** [comment]
I value your thoughts and continue to muse on them.

I'm thinking about the the simplest elegant approach.
- We always generate both a URL slug and an SMS, etc. token on verify and reset. This reduces the complexity of the user item.
- The onus therefore is on the emailer to decide which one to send and how. The decision may be based on a user property or determined dynamically.
- The URL slug path remains logically the same. On success or failure both tokens are erased.
- We have another logical path which accepts { username, smsToken } or { email, smsToken }. On success or failure the SMS token is erased. I would also erase the slug token but there be a reason not to.

Cons:
- Emailer needs to be able to determine if the user preferred the slug or SMS. Can you visualize a situation where a user property would not suffice?
- Allows a hacker to try a lower complexity SMS token on any account. Are the mathimatical odds high enough to be of concern?

I await your comments.

**Comment by beeplin** [comment]
1. I support your idea. The only thing is the name smsToken. Since it is not necessarily used for sms (may be email or other channels too), maybe shortToken is a better name.
2. for the first con: as I said, there is time when user uses email but still want to receive a short code via email and then input it in our app rather than clicking a url. Here we cannot judge the type of slug\shortToken only by user property. 'email' does not always mean slug, 'cellphone' does not always mean shorttoken. we could determine in the frontend code which way to use, or let user choose when they sign up or try to reset password.
3. for the second con: two ways to cope with this: first, the short token could be not only digits but a mixture of digits, lowercase letters and uppercase letters. or even with @#%: characters, as long as people can easily input it  via their cellphone keyboards.

second, when verifying, ask user to provide password together with username and token. when resetting password, ask user to provide username, email\cellphone (the address he just asked the token to send to), and the token altogether.

**Comment by eddyystop** [comment]
So we go with `verifyShortToken` and `resetShortToken`.

We could use `app.configure(verifyReset({ shortTokenType: 'digits' | 'alpha' }));` to specify what shortToken consists of.

I can look into the client API having a param object which is passed through to the emailer. The client could use this to indicate the transport to be used, and that could be set dynamically.

I like your idea of providing additional info for confirmation when verifying a short token. I am thinking of delaying an implementation until its need becomes clear. A 6 alpha-char token valid only for accounts that have not yet been verified, or which have an outstanding password request seems like good starting odds.

**Comment by eddyystop** [comment]
You can download the sms-support branch from GitHub. I believe all features we discussed have been implemented. The docs in src/index.js are complete and up-to-date.

I will update the other docs and I await your comments before pushing this to the master branch.

I have added docs on how to use this repo with Redux.

I see you might be using Vue. Perhaps you might provide some info on how to integrate with Vue. I am personally interested in Vue 2.0 now that they have announced the possibility of authorized mobile widgets.

**Comment by beeplin** [comment]
will check it asap.

any link about this?

> I am personally interested in Vue 2.0 now that they have announced the possibility of authorized mobile widgets

**Comment by beeplin** [comment]
wow this is a pretty bit rewrite! I really appreciate the promise-based code style. the `.then` chain shows the logic in a very clear way.

Currently I have no chance to download and test the new branch, but I read the code on github, and yes, I think all features mentioned before have been implemented with nice APIs. 👍 

As for vue integration: I checked your `feathers-reduxify-service` repo and that's amazing. Just like react has redux, Vue has a very similar tool called `vuex`, which is officially supported by Vue's core team and widely used. Here are its [repo](https://github.com/vuejs/vuex) and [docs](http://vuex.vuejs.org/en/index.html). It has a basic concept borrowed from redux (store, state, mutations, actions, dispatch... with a little bit difference), and its implementation is much simpler since Vue achieves reactivity via object's setter/getter rather than updating the whole v-dom each time the state changes. You could go through its docs in half an hour and it's really simple.

I am imagining to see a new repo `feathers-vuexify-service` coming... :))))

**Comment by beeplin** [comment]
BTW, vuex has a similar devtool for chrome, providing debug features like time-travel. As cool as redux does.

**Comment by beeplin** [comment]
BTW, vue/vuex has a similar [devtool for chrome](https://github.com/vuejs/vue-devtools), providing debug features like time-travel. As cool as redux does.

**Comment by eddyystop** [comment]
https://medium.com/the-vue-point/vue-2-0-is-here-ef1f26acf4b8#.40ab3c7ne talks about Vue 2.0

"we have started an official collaboration to make Vue 2.0 the actual JavaScript runtime framework for Weex [Alibaba project which renders components written in a Vue-inspired syntax into native mobile UI]. This will enable users to write universal Vue components that can be reused across Web, iOS and Android! The collaboration is still in early stages, but it will be a big focus for us now that 2.0 is out, so stay tuned!"

Our company uses React for React Native. I'm now interested in Vue because I suspect React perhaps is over-engineered.

**Comment by beeplin** [comment]
yeah I know the weex project. It's initiated by some engineers from alibaba in China, and now yyx (vue leader) is working with them on this project. Currently it is not as mature as react-native (but in my opinion react-native is far from mature too).

I agree that react might be over-engineered. That is why I prefer vue 2.0 which could do basically everything react can do, in a much more straightforward way.

**Comment by beeplin** [comment]
Since we are talking about Vue... these days I am looking for a neat way to connect feathers from backend and vue on the frontend. It should support socket.io real-time data push, and it would be nice to have a middle data layer to do client-side data cache (both in memory and on disk via localforage). 

For the cache thing, I am now working on a repo called `feathers-cache`, which will create client-side services as a buffer layer to cache and proxy remote services to Vue or React or any other frontend engines. 

For the vue-feathers syncing thing, it seems that we get three ways to do that:
1. by doing something like your `feathers-reduxify-service` for vue/vuex. While not every one uses vuex. Personally I think vuex might be over-engineered too.
2. by bridging vue and feathers via RxJS observables. Currently we have vue-rx and feathers-reactive out of box, and it works fine. Only that it lacks some commonly needed feathers: reactive loading/saving flags, auto reloading when query changes, etc.
3. by writing a specific sync tool. Now we have [vue-syncers-feathers](https://github.com/t2t2/vue-syncers-feathers) by @t2t2, and I wrapped it a little as [vue-feathers-sync](https://github.com/beeplin/vue-feathers-sync), adding some trivial extra features. 

I am still trying to figure out which way will be the best. But I guess once these infrastructures (sync, cache, user verify/reset) are ready, feathers with vue would become a super powerful full-stack framework. (I know there is `canjs` for feathers but vue seems much more promising at the frontend.)

**Comment by eddyystop** [comment]
Thanks for the info. I'll look into your comments in a while.

You may want to look into https://github.com/eddyystop/feathers-live-query . It shows how to keep an up-to-date copy on the client of part of a server table.

**Comment by beeplin** [comment]
I just released [https://github.com/beeplin/feathers-cache](https://github.com/beeplin/feathers-cache) which seems to work fine. :)

**Comment by eddyystop** [comment]
I posted it on the core-team slack channel.

**Comment by beeplin** [comment]
A new vue-feathers sync (or hotload) tool just finished: [vue-feathers-hotload](https://github.com/beeplin/vue-feathers-hotload). Together with the previous `feather-cache` it can do some fancy stuff in vue~

It borrows @t2t2 's API design, but achieves the same effect with much less code  by making use of RxJS via feathers-reactive. So basically I chose the second way (the rxjs way) but improved it with features coming from the third.

**Comment by eddyystop** [comment]
Nice. I look forward to looking into it.

Don't forget to add your repos to https://docs.feathersjs.com/why/showcase.html

I will push feathers-service-verify-reset 1.0.0 today

**Comment by beeplin** [comment]
I will test the repos a little bit more to see if they are sound enough to go public. :)

Looking forward to feathers-service-verify-reset 1.0.0!

**Comment by eddyystop** [comment]
Pushed 1.0.0. It fixes many issues found in the `sms-support` branch.
