### ISSUE TITLE
Verify email REST route not working without client code

### ISSUE THREAD

**Issue by vgeorge** [eddyystop/feathers-service-verify-reset#2]
At the example the REST route for verifyToken is created by proxying the request via client code. I've incorporated the server code to my app and the module fails to setup a valid GET for token verification via REST. [This code](https://github.com/eddyystop/feathers-service-verify-reset/blob/master/src/index.js#L65) defines the route `/verifyReset/:action/:value`, but it is only acessible via POST requests because it uses `create` method.

**Comment by eddyystop** [comment]
Thanks for the info. I'll look into it soon.

**Comment by eddyystop** [comment]
I'm unclear if you are using Feathers at all on the client. Specifically, are you doing a `app.configure(feathers.authentication())` on the **client**?

The following assumes you are not:

The server-side of this repo lets feathers-authentication (server version) handle the initial authentication.

You can still interface with feathers-authentication (server version) if you are not using Feathersjs on the client. See the [authentication over rest](http://docs.feathersjs.com/authentication/readme.html#authentication-over-rest) section.

You may also consider using something like this on the client:

``` javascript
// <script src="//npmcdn.com/feathers-client@^1.4.1/dist/feathers.js"></script>
const app = feathers()
  .configure(feathers.rest(...))
  .configure(feathers.authentication({ storage: window.localStorage }));
```

which gives you access to `app.authenticate({ type: 'local', email, password });` which let's this repo work as intended. You can use raw HTTP for other all other fetches.

Lemme know what happens.
