### ISSUE TITLE
client service wrappers don't return promise

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#20]
The docs said: 
> The wrappers return a Promise unless a callback is provided. See example/ for a working example of wrapper usage.

but actually in `client.js`, for example:

```js
	this.emailChange = (password, email, user, cb) => {
		verifyReset.create({
			action: 'emailChange',
			value: {
				password,
				email
			},
		}, {
			user
		}, cb);
	};
```

These wrappers return nothing. should be:

```js
	this.emailChange = (password, email, user, cb) => {
		return verifyReset.create({ // add 'return' here
			action: 'emailChange',
			value: {
				password,
				email
			},
		}, {
			user
		}, cb);
	};
```

**Comment by eddyystop** [comment]
Thanks. I'll look into this when I'm free.

**Comment by eddyystop** [comment]
v1.0.1: `client.js` now returns Promises as documented

`wrapper.test.js` effectively no-op'ed all its callback tests, testing nothing. This was fixed. Tests for promises were added.
