### ISSUE TITLE
verify-reset on another service

### ISSUE THREAD

**Issue by alex-bashkatov-ezlo** [eddyystop/feathers-service-verify-reset#23]
Hi, first of all thank you for this awesome utils!
I ran into situation where I need to have almost all `users` functionality but name my service e.g. `customers` instead of `users` for project reasons.
As far as I get from this line https://github.com/eddyystop/feathers-service-verify-reset/blob/master/src/index.js#L390
`users` is a must.
Do you consider adding smth like `options.servicePath` to make it play with some other services?

**Comment by eddyystop** [comment]
Hi. This repo has been absorbed, with enhancements, by Feathers and renamed feathers-authentication-managment. Please use that as any enhancements occur there. 

https://docs.feathersjs.com/api/authentication/local-management.html

It has the option "service: The path of the service for user items, e.g. /users (default) or /organization."

**Comment by alex-bashkatov-ezlo** [comment]
cool, thanks for pointing to
