### ISSUE TITLE
Question on userNotifier interface migration

### ISSUE THREAD

**Issue by aplb** [eddyystop/feathers-service-verify-reset#25]
Hi folks,
I've upgraded from 0.8 to the latest version and ran into the following pitfall with userNotifier.
Initially, my goal is send emails using `hostname`, thus I have the following middleware:
```js
.configure(socketio(io => {
    io.use((socket, next) => {
      socket.feathers.hostname = socket.request.headers.host;
      next();
    });
}))
```
Cause signature userNotifier was `(type, user1, params, cb)`, I just grabbed host from hook.params.
ATM, userNotifier is employed like
```js
userNotifier('sendResetPwd', user, notifierOptions)
// or
userNotifier('resetPwd', user1)
```
I'm looking for good solution how to connect past and current )
Thanks in advance

**Comment by eddyystop** [comment]
You can write a promise to callback wrapper. There may be one in the common hooks. Maybe named primsetocallback.


Sent from my Samsung device

-------- Original message --------

**Comment by alex-bashkatov-ezlo** [comment]
do you mean wrap with promise emailer which is `function (action, user, params, newEmail, cb)`?
I probably miss how callback-to-promise will deliver hook.params if emailer is called e.g. in resetPassword `userNotifier('resetPwd', user1)`

**Comment by aplb** [comment]
sorry I miss, which block do you mean to wrap?

**Comment by aplb** [comment]
do you mean wrap into promise emailer `function (action, user, params, newEmail, cb)`?
I probably miss how this will deliver hook.params if emailer is called e.g. in resetPassword `userNotifier('resetPwd', user1)`

**Comment by eddyystop** [comment]
You were using a legacy func which had a callback. The current func returns
a promise. You can wrap that current func so that the wrapper uses a
callback. Calling the wrapper will make the current func act like the old
one.

Here's code for such a generalized wrapper:
```js

const asap = process && typeof process.nextTick === 'function'
  ? process.nextTick : setImmediate;

module.exports = function (promise) {
  return cb => {
    promise.then(
      data => {
        asap(cb, null, data);
        return data;
      },
      err => {
        asap(cb, err);
      });

    return null;
  };
};

```
