### ISSUE TITLE
password-resetting not working in the example?

### ISSUE THREAD

**Issue by beeplin** [eddyystop/feathers-service-verify-reset#8]
i am trying the example and the verification runs smoothly, but when resetting password, the token is like: `http://localhost:3030/rest/reset/undefined`, and the procedure failed. 

Do I did something wrong? I just created a new account, verified it, signed in, logged out, and then clicked the reset password button.

**Comment by eddyystop** [comment]
I will look into it shortly.

**Comment by beeplin** [comment]
thanks~

**Comment by eddyystop** [comment]
The example had not kept pace with the service and the tests. Fixed now.

You might notice the example no longer displays the password reset URL on the browser, only on the server console. The service had been changed to prevent that vulnerability.
